env:
    credentials: "ENCRYPTED[!038f5a66efec8b6d1a467fb1abeac192efb01db8482aae81b0fdee87cad930ed65fd0d026f21aaf26b22879fc65d4136!]"
    rcloneconfig: "ENCRYPTED[!2d3be29b89b2b1c9819222d8949896f49fd5a6ae8f0cfbbb4915fcb6b9bf6e978f928fbe16f5be39c63b8101499826f5!]"
    tokentl: "ENCRYPTED[!457fc657d89b16fb0c6cb05358ebf7e2c6b7af06207fcd9b6fe0adac021c2f539235bcdb6ceef3710e3c15acf20876ae!]"
    idtl: "ENCRYPTED[!c8bfd556307d9518ad8554a0b95a924e968283f96d82d837da01e629d6a37ad5a6aca5d0485d7f7920fa095ef4e9b5f2!]"
    lunch: lunch qassa_onclite-userdebug
    make: make qassa

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G

  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.rclone.conf
       - git config --global user.name "LizRelDev"
       - git config --global user.email "dimasmiftah093@gmail.com"
       - echo "$credentials" > ~/.git-credentials
       - git config --global credential.helper store --file=~/.git-credentials
       - mkdir -p ~/ccache
       - rclone copy cirrus:qassa/ccache.tar.gz ~/ -P
       - cd ~/
       - time tar xf ccache.tar.gz
       - cd ~/

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
      - ./w.sh

  Sync_script:
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Start sync qassa Source"
      - mkdir -p ~/rom
      - cd ~/rom
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/keepQASSA/manifest.git -b Q -g default,-mips,-darwin,-notdefault
      - git clone --depth 1 https://github.com/LizRelDev/local_manifest.git -b qassa-onclite .repo/local_manifests
      - sed -i 's|ssh://git@github.com|https://github.com|g' .repo/manifests/snippets/qassa.xml
#      - repoo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8 --fail-fast
      - repo sync -c -j8 --force-sync --no-clone-bundle --no-tags
      - sed -i 's| -u||g' vendor/qassa/config/branding.mk
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Sync Completed!"

  Build_script:
      - export BUILD_USERNAME="LizRelDev-ci"
      - export BUILD_HOSTNAME="LizRelDev"
      - export KBUILD_BUILD_USER="LizRelDev-ci"
      - export KBUILD_BUILD_HOST="LizRelDev"
#      - export WITH_GAPPS=false
      - sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build qassa onclite Started!"
      - ./collect.sh
#      - ./final.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd ~/rom/out/target/product/onclite/ && ls qassa_*.zip) Completed!"

  Upload_script:
      - ./upload.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Compres ccache"
      - ./ziping.sh
      - cd ~/
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading ccache...."
      - rclone copy ccache.tar.gz cirrus:qassa -P
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Ccache Uploaded Successfully!"

